const white = 0xEEEEEE;
const red = 0xFF1111;
const blue = 0x1111FF;
const black = 0x111111;

const keys = [
  [
    {
      label: 'A♭',
      name: 'minor second',
      ratio: 16 / 15,
      color: black,
      textColor: white,
    },
    {
      label: 'B♭',
      name: 'minor third',
      ratio: 6 / 5,
      color: black,
      textColor: white,
    },
    {
      label: 'C',
      name: 'dominant perfect fourth',
      ratio: 21 / 16,
      color: red,
      textColor: black,
    },
    {
      label: 'D♭',
      name: 'diminished fifth',
      ratio: 64 / 45,
      color: black,
      textColor: white,
    },
    {
      label: 'E♭',
      name: 'minor sixth',
      ratio: 8 / 5,
      color: black,
      textColor: white,
    },
    {
      label: 'F',
      name: 'dominant minor seventh',
      ratio: 7 / 4,
      color: red,
      textColor: black,
    },
    {
      label: 'G♭',
      name: 'diminished octave',
      ratio: 48 / 25,
      color: black,
      textColor: white,
    },
  ],
  [
    {
      label: 'G♯',
      name: 'augmented unison',
      ratio: 25 / 24,
      color: black,
      textColor: white,
    },
    {
      label: 'A♯',
      name: 'augmented second',
      ratio: 75 / 64,
      color: black,
      textColor: white,
    },
    {
      label: 'B♯',
      name: 'augmented third',
      ratio: 125 / 96,
      color: white,
      textColor: black,
    },
    {
      label: 'C♯',
      name: 'augmented fourth',
      ratio: 45 / 32,
      color: black,
      textColor: white,
    },
    {
      label: 'D♯',
      name: 'augmented fifth',
      ratio: 25 / 16,
      color: black,
      textColor: white,
    },
    {
      label: 'E♯',
      name: 'augmented sixth',
      ratio: 225 / 128,
      color: white,
      textColor: black,
    },
    {
      label: 'F♯',
      name: 'major seventh',
      ratio: 15 / 8,
      color: black,
      textColor: white,
    },
  ],
  [
    {
      label: 'G',
      name: 'perfect unison',
      ratio: 1,
      color: white,
      textColor: black,
    },
    {
      label: 'A',
      name: 'major second',
      ratio: 9 / 8,
      color: white,
      textColor: black,
    },
    {
      label: 'B',
      name: 'major third',
      ratio: 5 / 4,
      color: white,
      textColor: black,
    },
    {
      label: 'C',
      name: 'perfect fourth',
      ratio: 27 / 20,
      color: white,
      textColor: black,
    },
    {
      label: 'D',
      name: 'perfect fifth',
      ratio: 3 / 2,
      color: white,
      textColor: black,
    },
    {
      label: 'E',
      name: 'major sixth',
      ratio: 27 / 16,
      color: white,
      textColor: black,
    },
    {
      label: 'F',
      name: 'minor seventh',
      ratio: 9 / 5,
      color: white,
      textColor: black,
    },
  ],
  [
    {
      label: 'G',
      name: 'dominant perfect unison',
      ratio: 63 / 64,
      color: red,
      textColor: black,
    },
    {
      label: 'A',
      name: 'lesser major second',
      ratio: 10 / 9,
      color: blue,
      textColor: white,
    },
    {
      label: 'C♭',
      name: 'diminished fourth',
      ratio: 32 / 25,
      color: white,
      textColor: black,
    },
    {
      label: 'C',
      name: 'lesser perfect fourth',
      ratio: 4 / 3,
      color: blue,
      textColor: white,
    },
    {
      label: 'D',
      name: 'lesser perfect fifth',
      ratio: 40 / 27,
      color: blue,
      textColor: white,
    },
    {
      label: 'E',
      name: 'lesser major sixth',
      ratio: 5 / 3,
      color: blue,
      textColor: white,
    },
    {
      label: 'F',
      name: 'lesser major seventh',
      ratio: 16 / 9,
      color: blue,
      textColor: white,
    },
  ],
];

export default keys;
